/*****************************************************************************************************************/
/*												auto generated defines (do not modify):												  */
/*****************************************************************************************************************/
 
`define N 1024
`define Nx 514
`define Nh 511
`define BANK_SIZE 256
`define WIDTH_RAM 10
`define DEPTH_ROM 64
`define LAST_STAGE 9
`define LAST_STAGE_ODD
 
`define ADC_WIDTH 16
`define D_BIT 20
`define A_BIT 8
`define W_BIT 13
`define CONV_BIT 24
`define IMP_BIT 17
 
`define MAX_ADC_D 32768
`define MAX_D 524288
`define MAX_W 2048
`define MAX_CONV 8388608
`define MAX_IMP 32768
 
 
/*****************************************************************************************************************/
/*																	work directories:															  */
/*****************************************************************************************************************/
// init RAM files for FPGA in reg type:
	`define INIT_FHT_RAM	"../../fht/matlab/init_fht_ram.txt"			// input for FHT, defined by choosed test in matlab
	`define INIT_CONV_RAM	"../../fht_conv/matlab/init_conv_ram.txt"	// input for conv tb (signal after FHT), generated by 'fht.m' in test 'imp' and 'signal' modes
	`define INIT_IMP_P_RAM	"../../fht_conv/matlab/init_imp_p_ram.txt"
	`define INIT_IMP_N_RAM	"../../fht_conv/matlab/init_imp_n_ram.txt"

// output MATH files for compare in real type (for data):
	`define MATH_FHT_RAM	"../../fht/matlab/math_fht_ram.txt"			// math model FHT out RAM for compare
	`define MATH_CONV_RAM	"../../fht_conv/matlab/math_conv_ram.txt"	// math model CONV by DHT out RAM for compare
	`define MATH_CONV_ADDR	"../../fht_conv/matlab/math_conv_addr.txt"
	`define MATH_ADDR_RD	"../../fht/matlab/math_addr_rd.txt"			// addr of math model RAM on different stages FHT for compare
	`define MATH_ADDR_WR	"../../fht/matlab/math_addr_wr.txt"

// output FPGA file for compare in real and reg type (save 'reg' version of RAM - prescript 'reg' is added to the entered name automatic):
	`define FPGA_FHT_RAM	"fpga_fht_ram.txt"	// FHT output from tb save in current dir of modelsim project
	`define FPGA_CONV_RAM	"fpga_conv_ram.txt"	// CONV output (ready for IFHT RAM) from tb save in current dir of modelsim project

`ifdef MODEL_TECH
	`define MIF_SIN "../../fht/sin.mif"
	`define MIF_COS "../../fht/cos.mif"
`else
	`define MIF_SIN "./sin.mif"
	`define MIF_COS "./cos.mif"
`endif

/*****************************************************************************************************************/
/*													variable defines for testbench and rtl:											  */
/*****************************************************************************************************************/

// `define TEST_MIXER // check only 'top' + 'control', RAM data (0..N) "avoid" butterfly and multipliers
// `define EN_BREAKPOINT
`define COMPARE_WITH_MATLAB

// if modelsim issue error 'Unresolved reference to...' try to switch this define:
	// `define RAM_ACCESS_TB altsyncram_component.mem_data
	`define RAM_ACCESS_TB altsyncram_component.m_default.altsyncram_inst.mem_data
	// `define RAM_ACCESS_TB altsyncram_component.m_non_arria10.altsyncram_inst.mem_data

`define ROUND_FHT			// enable round in FHT butterfly
`define ROUND_FHT_CONV	// enable round in conv calc

`define CLK_FREQ 100 // MHz

`define TACT		$ceil(1000/`CLK_FREQ) // ns
`define HALF_TACT	$ceil(`TACT/2)
/*
`define TACT 21
`define HALF_TACT `TACT/2 
*/
`define NUM_OF_RPT 50	// number of repeat butterfly test
`define ACCURACY 0.001	// for all tests (butterfly, FHT)