# TCL File Generated by Component Editor 13.0sp1
# Thu Jul 23 12:16:38 MSD 2020
# DO NOT MODIFY


# 
# FHT "FHT" v1.0
# SS 2020.07.23.12:16:38
# Configurable fast Hartley transform
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1

set_module_property VALIDATION_CALLBACK validate
proc validate {} {
	set pA_BIT [get_parameter_value A_BIT]
	set pD_BIT [expr [get_parameter_value D_BIT] + 1]
	set pW_BIT [expr [get_parameter_value W_BIT] + 1]

	set pN [expr int(4*pow(2, $pA_BIT))] 
	set BANK_SIZE [expr $pN/4]
		
	set MAX_D [expr int(pow(2, $pD_BIT - 2))]
	set MAX_W [expr int(pow(2, $pW_BIT - 2))]	

	set DEPTH_NUM_STAGE	[expr int(log($pA_BIT)/log(2))]
	set DEPTH_ROM		[expr int(pow(2, $pA_BIT - 2))]
	set LAST_STAGE		[expr int(log($pN)/log(2) - 1)] 
		
	set path_def ./fht_defines.v
	set f_def [open $path_def r+]

		puts $f_def "/*******************************************/"
		puts $f_def "/* auto generated defines (do not modify): */"
		puts $f_def "/*******************************************/"
		puts $f_def " "
		puts $f_def "`define N $pN"
		puts $f_def "`define BANK_SIZE $BANK_SIZE"
		puts $f_def "`define DEPTH_NUM_STAGE $DEPTH_NUM_STAGE"
		puts $f_def "`define DEPTH_ROM $DEPTH_ROM"
		puts $f_def "`define LAST_STAGE $LAST_STAGE"
		puts $f_def " "
		puts $f_def "`define D_BIT $pD_BIT"
		puts $f_def "`define A_BIT $pA_BIT"
		puts $f_def "`define W_BIT $pW_BIT"
		puts $f_def " "
		puts $f_def "`define MAX_D $MAX_D"
		puts $f_def "`define MAX_W $MAX_W"
		puts $f_def " "
		puts $f_def "/*******************************************/"
		puts $f_def " "

	close $f_def
}

# 
# module FHT
# 
set_module_property DESCRIPTION "Configurable fast Hartley transform"
set_module_property NAME FHT
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DSP
set_module_property AUTHOR SS
set_module_property DISPLAY_NAME FHT
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fht_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file fht_but.v VERILOG PATH fht_but.v
add_fileset_file fht_but_block.v VERILOG PATH fht_but_block.v
add_fileset_file fht_control.v VERILOG PATH fht_control.v
add_fileset_file fht_defines.v VERILOG PATH fht_defines.v
add_fileset_file fht_in_mix.v VERILOG PATH fht_in_mix.v
add_fileset_file fht_ram.v VERILOG PATH fht_ram.v
add_fileset_file fht_ram_block.v VERILOG PATH fht_ram_block.v
add_fileset_file fht_rom.v VERILOG PATH fht_rom.v
add_fileset_file fht_rom_block.v VERILOG PATH fht_rom_block.v
add_fileset_file fht_top.v VERILOG PATH fht_top.v TOP_LEVEL_FILE


# 
# parameters
# 

add_parameter A_BIT INTEGER 8
set_parameter_property A_BIT DEFAULT_VALUE 8
set_parameter_property A_BIT DISPLAY_NAME "Address width"
set_parameter_property A_BIT DESCRIPTION "Defines number of point transform (N = 4*2^(Addr)), \
															it is depth of 1 of 4 bank RAM \
															(Addr - N; 4 - 64; 5 - 128; 6 - 256; 7 - 512; 8 - 1024; 9 - 2048; 10 - 4096)"
set_parameter_property A_BIT TYPE INTEGER
set_parameter_property A_BIT UNITS bits
set_parameter_property A_BIT ALLOWED_RANGES \
{5 6 7 8 9 10}
set_parameter_property A_BIT HDL_PARAMETER true

add_parameter D_BIT INTEGER 16
set_parameter_property D_BIT DEFAULT_VALUE 16
set_parameter_property D_BIT DISPLAY_NAME "ADC data width"
set_parameter_property D_BIT DESCRIPTION "Without extended bit"
set_parameter_property D_BIT TYPE INTEGER
set_parameter_property D_BIT UNITS bits
set_parameter_property D_BIT ALLOWED_RANGES \
{12 16 20 24 32}
set_parameter_property D_BIT HDL_PARAMETER true

add_parameter W_BIT INTEGER 15
set_parameter_property W_BIT DEFAULT_VALUE 15
set_parameter_property W_BIT DISPLAY_NAME "Twiddle coef data width"
set_parameter_property W_BIT DESCRIPTION "Without extended bit, allow from 12 to 20"
set_parameter_property W_BIT TYPE INTEGER
set_parameter_property W_BIT UNITS bits
set_parameter_property W_BIT ALLOWED_RANGES 12:20
set_parameter_property W_BIT HDL_PARAMETER true

add_parameter MIF_SIN STRING ./matlab/sin.mif
set_parameter_property MIF_SIN DEFAULT_VALUE ./matlab/sin.mif
set_parameter_property MIF_SIN DISPLAY_NAME MIF_SIN
set_parameter_property MIF_SIN TYPE STRING
set_parameter_property MIF_SIN UNITS None
set_parameter_property MIF_SIN HDL_PARAMETER true

add_parameter MIF_COS STRING ./matlab/cos.mif ""
set_parameter_property MIF_COS DEFAULT_VALUE ./matlab/cos.mif
set_parameter_property MIF_COS DISPLAY_NAME MIF_COS
set_parameter_property MIF_COS WIDTH ""
set_parameter_property MIF_COS TYPE STRING
set_parameter_property MIF_COS UNITS None
set_parameter_property MIF_COS DESCRIPTION ""
set_parameter_property MIF_COS HDL_PARAMETER true


# 
# display items
# 
add_display_item ROM MIF_SIN PARAMETER ""
add_display_item ROM MIF_COS PARAMETER ""


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink iCLK clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink iRESET reset Input 1


# 
# connection point FHT
# 
add_interface FHT conduit end
set_interface_property FHT associatedClock clock_sink
set_interface_property FHT associatedReset reset_sink
set_interface_property FHT ENABLED true
set_interface_property FHT EXPORT_OF ""
set_interface_property FHT PORT_NAME_MAP ""
set_interface_property FHT SVD_ADDRESS_GROUP ""

add_interface_port FHT iSTART export Input 1
add_interface_port FHT iWE export Input 4
add_interface_port FHT iDATA export Input "D_BIT + 1"

add_interface_port FHT oDATA_0 export Output "D_BIT + 1"
add_interface_port FHT oDATA_1 export Output "D_BIT + 1"
add_interface_port FHT oDATA_2 export Output "D_BIT + 1"
add_interface_port FHT oDATA_3 export Output "D_BIT + 1"

add_interface_port FHT iADDR_WR export Input A_BIT
add_interface_port FHT iADDR_RD_0 export Input A_BIT
add_interface_port FHT iADDR_RD_1 export Input A_BIT
add_interface_port FHT iADDR_RD_2 export Input A_BIT
add_interface_port FHT iADDR_RD_3 export Input A_BIT

add_interface_port FHT oRDY export Output 1